import { connectToDatabase } from "../../../util/mongodb";

export default async (req, res) => {
  const { db } = await connectToDatabase();

  db.collection("products").insertOne({
    itemID: "#10000",
    invoiceNumber: "",
    invoicePaid: false,
    apparel: false,
    status: "New Order",
    statusEditor: "",
    printer: "No Assigned Printer",
    printerTime: "",
    createdDate: "1/13/2021",
    arrivalDate: "1/20/2021",
    orderName: "Order One",
    orderCustomer: "Customer Name",
    orderAgent: "Customer Agent",
    orderMultiplePages: false,
    orderType: "Order Type",
    orderTypeNotes: "",
    setup: "",
    setupScreens: "",
    setupScreen: "",
    setupNotes: "",
    proof: [
      "https://cdn.shopify.com/s/files/1/1663/2287/products/blank_8a017003-4834-4e04-8979-d18c665db0ed_540x.png",
    ],
    proofNotes: "",
    art: [
      "https://cdn.shopify.com/s/files/1/1663/2287/products/blank_8a017003-4834-4e04-8979-d18c665db0ed_540x.png",
    ],
    artLink:
      "https://cdn.shopify.com/s/files/1/1663/2287/products/blank_8a017003-4834-4e04-8979-d18c665db0ed_540x.png",
    artSize: false,
    artNotes: "",
    positionFront: "",
    positionBack: "",
    positionRightLeft: "",
    positionAdditional: "",
    positionMatchProof: false,
    positionNotes: "",
    colorsPantone1: "",
    colorsPantone2: "",
    colorsPantone3: "",
    colorsColor1: "",
    colorsColor2: "",
    colorsColor3: "",
    colorsMatchProof: false,
    colorsNotes: "",
    arrivalTime: "7 - 10 days",
    arrivalRequestDate: "",
    arrivalHardDueDate: false,
    paymentInvoiceUrl: "",
    paymentNotes: "",
    paymentTerms: false,
    shipName: "",
    shipAttn: "",
    shipAddress: "",
    shipState: "",
    shipZipCode: "",
    shipEmail: "",
    shipPhone: "",
    shipPickup: false,
    shipMethod: "",
    shipTrackingUrl: "",
    shipNotes: "",
    shipLabel: "",
    shipPackingList: "",
    product1: {
      id: "1",
      men: false,
      woman: false,
      youth: false,
      other: false,
      otherName: "",
      pricePerPiece: "",
      tax: false,
      itemNumber: "",
      productType: "",
      color: "",
      additionalDescription: "",
      apparelSource: "",
      XS: "",
      S: "",
      M: "",
      L: "",
      XL: "",
      XXL: "",
      XXXL: "",
      other1: "",
      other1PCS: "",
      other2: "",
      other2PCS: "",
      other3: "",
      other3PCS: "",
      other4: "",
      other4PCS: "",
    },
    product2: {
      id: "2",
      men: false,
      woman: false,
      youth: false,
      other: false,
      otherName: "",
      pricePerPiece: "",
      tax: false,
      itemNumber: "",
      productType: "",
      color: "",
      additionalDescription: "",
      apparelSource: "",
      XS: "",
      S: "",
      M: "",
      L: "",
      XL: "",
      XXL: "",
      XXXL: "",
      other1: "",
      other1PCS: "",
      other2: "",
      other2PCS: "",
      other3: "",
      other3PCS: "",
      other4: "",
      other4PCS: "",
    },
    product3: {
      id: "3",
      men: false,
      woman: false,
      youth: false,
      other: false,
      otherName: "",
      pricePerPiece: "",
      tax: false,
      itemNumber: "",
      productType: "",
      color: "",
      additionalDescription: "",
      apparelSource: "",
      XS: "",
      S: "",
      M: "",
      L: "",
      XL: "",
      XXL: "",
      XXXL: "",
      other1: "",
      other1PCS: "",
      other2: "",
      other2PCS: "",
      other3: "",
      other3PCS: "",
      other4: "",
      other4PCS: "",
    },
    product4: {
      id: "4",
      men: false,
      woman: false,
      youth: false,
      other: false,
      otherName: "",
      pricePerPiece: "",
      tax: false,
      itemNumber: "",
      productType: "",
      color: "",
      additionalDescription: "",
      apparelSource: "",
      XS: "",
      S: "",
      M: "",
      L: "",
      XL: "",
      XXL: "",
      XXXL: "",
      other1: "",
      other1PCS: "",
      other2: "",
      other2PCS: "",
      other3: "",
      other3PCS: "",
      other4: "",
      other4PCS: "",
    },
    product5: {
      id: "5",
      men: false,
      woman: false,
      youth: false,
      other: false,
      otherName: "",
      pricePerPiece: "",
      tax: false,
      itemNumber: "",
      productType: "",
      color: "",
      additionalDescription: "",
      apparelSource: "",
      XS: "",
      S: "",
      M: "",
      L: "",
      XL: "",
      XXL: "",
      XXXL: "",
      other1: "",
      other1PCS: "",
      other2: "",
      other2PCS: "",
      other3: "",
      other3PCS: "",
      other4: "",
      other4PCS: "",
    },
  });

  res.statusCode = 201;
  res.json("Item Created");
};
